version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: dev # for Dockfile
    volumes:
      - ./:/app
      - /app/node_modules # this is a hack for disabling volumn binding sync issue
    environment:
      - NODE_ENV=dev
    command: yarn dev